{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "zwebapp.serviceAccountName" . }}
  labels:
{{ include "zwebapp.labels" . | indent 4 }}
{{- end -}}
