apiVersion: v1
kind: Service
metadata:
  name: {{ include "zwebapp.fullname" . }}
  labels:
{{ include "zwebapp.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "zwebapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
